#!/usr/bin/env bash

###############################################################################
# Remote SSH Connection Setup and Management
# Configures SSH access to remote RHEL nodes
###############################################################################

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }
log_section() { echo -e "\n${CYAN}═══════════════════════════════════════════════════${NC}"; echo -e "${CYAN}$1${NC}"; echo -e "${CYAN}═══════════════════════════════════════════════════${NC}\n"; }

SSH_DIR="$HOME/.ssh"
CONFIG_FILE="$SSH_DIR/config"
KNOWN_HOSTS="$SSH_DIR/known_hosts"

log_section "Remote SSH Connection Setup"

###############################################################################
# Setup SSH keys
###############################################################################
setup_ssh_keys() {
    log_step "Setting up SSH keys..."
    
    mkdir -p "$SSH_DIR"
    chmod 700 "$SSH_DIR"
    
    # Check if key exists
    if [ ! -f "$SSH_DIR/id_rsa" ]; then
        log_info "Generating new SSH key pair..."
        ssh-keygen -t rsa -b 4096 -f "$SSH_DIR/id_rsa" -N "" -C "devops@$(hostname)"
        log_info "✅ SSH key pair generated"
    else
        log_info "SSH key pair already exists"
    fi
    
    # Set permissions
    chmod 600 "$SSH_DIR/id_rsa"
    chmod 644 "$SSH_DIR/id_rsa.pub"
    
    log_info "Public key:"
    cat "$SSH_DIR/id_rsa.pub"
}

###############################################################################
# Configure SSH config file
###############################################################################
configure_ssh_config() {
    log_step "Configuring SSH client..."
    
    # Backup existing config
    if [ -f "$CONFIG_FILE" ]; then
        cp "$CONFIG_FILE" "$CONFIG_FILE.backup.$(date +%Y%m%d_%H%M%S)"
    fi
    
    # Create/update config
    cat > "$CONFIG_FILE" << 'EOF'
# SSH Client Configuration for DevOps
# Generated by remote-ssh-setup.sh

# Default settings for all hosts
Host *
    ServerAliveInterval 60
    ServerAliveCountMax 3
    TCPKeepAlive yes
    Compression yes
    ControlMaster auto
    ControlPath ~/.ssh/control-%r@%h:%p
    ControlPersist 10m
    ForwardAgent yes
    StrictHostKeyChecking accept-new
    IdentityFile ~/.ssh/id_rsa

# Kubernetes Master Node
Host k8s-master k8s-master-1 master1
    HostName 192.168.1.101
    User root
    Port 22

# Kubernetes Worker Nodes
Host k8s-worker-1 worker1
    HostName 192.168.1.102
    User root
    Port 22

Host k8s-worker-2 worker2
    HostName 192.168.1.103
    User root
    Port 22

# Development Server
Host dev-server dev
    HostName 192.168.1.201
    User devops
    Port 22

# Staging Server
Host staging-server staging
    HostName 192.168.1.202
    User devops
    Port 22

# Production Server (with bastion)
Host prod-bastion bastion
    HostName 10.0.1.100
    User admin
    Port 22

Host prod-server prod
    HostName 10.0.2.100
    User devops
    Port 22
    ProxyJump prod-bastion

# Harbor Registry Server
Host harbor-registry harbor
    HostName 192.168.1.50
    User admin
    Port 22

# Example: Multi-hop connection
# Host final-destination
#     HostName 172.16.0.100
#     User admin
#     ProxyJump bastion,intermediate-host
EOF

    chmod 600 "$CONFIG_FILE"
    log_info "✅ SSH config created: $CONFIG_FILE"
}

###############################################################################
# Copy SSH key to remote hosts
###############################################################################
copy_key_to_host() {
    local host=$1
    local user=${2:-root}
    
    log_step "Copying SSH key to $user@$host..."
    
    if ssh-copy-id -i "$SSH_DIR/id_rsa.pub" "$user@$host" 2>/dev/null; then
        log_info "✅ SSH key copied to $user@$host"
        
        # Test connection
        if ssh -o ConnectTimeout=5 "$user@$host" "echo 'Connection successful'" &>/dev/null; then
            log_info "✅ SSH connection test passed"
        else
            log_warn "SSH key copied but connection test failed"
        fi
    else
        log_error "Failed to copy SSH key to $user@$host"
        log_info "Try manually: ssh-copy-id -i $SSH_DIR/id_rsa.pub $user@$host"
    fi
}

###############################################################################
# Batch copy keys
###############################################################################
batch_copy_keys() {
    log_step "Batch copying SSH keys to multiple hosts..."
    
    # Read hosts from input
    cat << 'EOF' > /tmp/ssh_hosts.txt
# Format: hostname|user|port
192.168.1.101|root|22
192.168.1.102|root|22
192.168.1.103|root|22
EOF

    log_info "Edit /tmp/ssh_hosts.txt with your hosts, then press Enter"
    read -p "Continue? (y/N): " -n 1 -r
    echo
    
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        while IFS='|' read -r host user port; do
            # Skip comments and empty lines
            [[ "$host" =~ ^#.*$ ]] && continue
            [[ -z "$host" ]] && continue
            
            log_info "Processing $user@$host:$port..."
            copy_key_to_host "$host" "$user"
        done < /tmp/ssh_hosts.txt
    fi
}

###############################################################################
# Test SSH connections
###############################################################################
test_connections() {
    log_step "Testing SSH connections..."
    
    # Extract configured hosts from SSH config
    HOSTS=$(grep "^Host " "$CONFIG_FILE" | grep -v "\*" | awk '{print $2}')
    
    for host in $HOSTS; do
        log_info "Testing connection to $host..."
        
        if timeout 5 ssh -o ConnectTimeout=3 "$host" "hostname" &>/dev/null; then
            echo -e "  ${GREEN}✅ $host${NC} - Connection successful"
        else
            echo -e "  ${RED}❌ $host${NC} - Connection failed"
        fi
    done
}

###############################################################################
# Setup SSH agent
###############################################################################
setup_ssh_agent() {
    log_step "Setting up SSH agent..."
    
    # Check if agent is running
    if [ -z "${SSH_AUTH_SOCK:-}" ]; then
        log_info "Starting SSH agent..."
        eval "$(ssh-agent -s)"
    else
        log_info "SSH agent already running"
    fi
    
    # Add key to agent
    ssh-add "$SSH_DIR/id_rsa" 2>/dev/null && \
        log_info "✅ SSH key added to agent" || \
        log_warn "Failed to add SSH key to agent"
    
    # Add to shell profile
    if ! grep -q "ssh-agent" ~/.bashrc; then
        cat >> ~/.bashrc << 'EOF'

# Start SSH agent automatically
if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent -s)" > /dev/null
    ssh-add ~/.ssh/id_rsa 2>/dev/null
fi
EOF
        log_info "✅ SSH agent auto-start added to ~/.bashrc"
    fi
}

###############################################################################
# Create SSH tunnel
###############################################################################
create_ssh_tunnel() {
    local remote_host=$1
    local local_port=$2
    local remote_port=$3
    local remote_target=${4:-localhost}
    
    log_step "Creating SSH tunnel..."
    log_info "Local: localhost:$local_port -> Remote: $remote_target:$remote_port via $remote_host"
    
    ssh -f -N -L "$local_port:$remote_target:$remote_port" "$remote_host"
    
    if [ $? -eq 0 ]; then
        log_info "✅ SSH tunnel created"
        log_info "Access service at: localhost:$local_port"
    else
        log_error "Failed to create SSH tunnel"
    fi
}

###############################################################################
# Setup SOCKS proxy
###############################################################################
setup_socks_proxy() {
    local remote_host=$1
    local local_port=${2:-1080}
    
    log_step "Setting up SOCKS proxy..."
    
    ssh -f -N -D "$local_port" "$remote_host"
    
    if [ $? -eq 0 ]; then
        log_info "✅ SOCKS proxy created on localhost:$local_port"
        log_info "Configure your browser to use SOCKS5 proxy: localhost:$local_port"
    else
        log_error "Failed to create SOCKS proxy"
    fi
}

###############################################################################
# Generate inventory file for Ansible
###############################################################################
generate_ansible_inventory() {
    log_step "Generating Ansible inventory..."
    
    cat > inventory.ini << 'EOF'
# Ansible Inventory
# Generated by remote-ssh-setup.sh

[kubernetes:children]
masters
workers

[masters]
master1 ansible_host=192.168.1.101 ansible_user=root

[workers]
worker1 ansible_host=192.168.1.102 ansible_user=root
worker2 ansible_host=192.168.1.103 ansible_user=root

[dev]
dev-server ansible_host=192.168.1.201 ansible_user=devops

[staging]
staging-server ansible_host=192.168.1.202 ansible_user=devops

[production]
prod-server ansible_host=10.0.2.100 ansible_user=devops ansible_ssh_common_args='-o ProxyJump=bastion'

[registry]
harbor-registry ansible_host=192.168.1.50 ansible_user=admin

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
EOF

    log_info "✅ Ansible inventory created: inventory.ini"
}

###############################################################################
# Show SSH info
###############################################################################
show_ssh_info() {
    log_section "SSH Configuration Summary"
    
    echo -e "${CYAN}SSH Key:${NC}"
    if [ -f "$SSH_DIR/id_rsa" ]; then
        echo "  ✅ Private key: $SSH_DIR/id_rsa"
        echo "  ✅ Public key: $SSH_DIR/id_rsa.pub"
        echo ""
        echo "Public key content:"
        cat "$SSH_DIR/id_rsa.pub"
    else
        echo "  ❌ No SSH key found"
    fi
    
    echo ""
    echo -e "${CYAN}SSH Config:${NC}"
    if [ -f "$CONFIG_FILE" ]; then
        echo "  ✅ Config file: $CONFIG_FILE"
        echo "  Configured hosts: $(grep "^Host " "$CONFIG_FILE" | grep -v "\*" | wc -l)"
    else
        echo "  ❌ No SSH config found"
    fi
    
    echo ""
    echo -e "${CYAN}SSH Agent:${NC}"
    if [ -n "${SSH_AUTH_SOCK:-}" ]; then
        echo "  ✅ SSH agent running"
        echo "  Loaded keys:"
        ssh-add -l 2>/dev/null || echo "  No keys loaded"
    else
        echo "  ❌ SSH agent not running"
    fi
}

###############################################################################
# Main menu
###############################################################################
main_menu() {
    while true; do
        log_section "Remote SSH Setup - Main Menu"
        
        echo "1. Setup SSH keys"
        echo "2. Configure SSH client"
        echo "3. Copy key to host"
        echo "4. Batch copy keys"
        echo "5. Test connections"
        echo "6. Setup SSH agent"
        echo "7. Create SSH tunnel"
        echo "8. Setup SOCKS proxy"
        echo "9. Generate Ansible inventory"
        echo "10. Show SSH info"
        echo "11. Exit"
        echo ""
        
        read -p "Select option: " choice
        
        case $choice in
            1) setup_ssh_keys ;;
            2) configure_ssh_config ;;
            3)
                read -p "Enter hostname: " host
                read -p "Enter username (default: root): " user
                user=${user:-root}
                copy_key_to_host "$host" "$user"
                ;;
            4) batch_copy_keys ;;
            5) test_connections ;;
            6) setup_ssh_agent ;;
            7)
                read -p "Remote host: " host
                read -p "Local port: " lport
                read -p "Remote port: " rport
                read -p "Remote target (default: localhost): " rtarget
                rtarget=${rtarget:-localhost}
                create_ssh_tunnel "$host" "$lport" "$rport" "$rtarget"
                ;;
            8)
                read -p "Remote host: " host
                read -p "Local port (default: 1080): " port
                port=${port:-1080}
                setup_socks_proxy "$host" "$port"
                ;;
            9) generate_ansible_inventory ;;
            10) show_ssh_info ;;
            11) log_info "Exiting..."; exit 0 ;;
            *) log_error "Invalid option" ;;
        esac
        
        echo ""
        read -p "Press Enter to continue..."
    done
}

###############################################################################
# Main execution
###############################################################################
case "${1:-menu}" in
    setup)
        setup_ssh_keys
        configure_ssh_config
        setup_ssh_agent
        show_ssh_info
        ;;
    menu)
        main_menu
        ;;
    test)
        test_connections
        ;;
    info)
        show_ssh_info
        ;;
    *)
        cat << EOF
Usage: $0 [command]

Commands:
  setup   - Complete SSH setup (keys + config + agent)
  menu    - Interactive menu (default)
  test    - Test all configured connections
  info    - Show SSH configuration info

Examples:
  $0 setup   # Complete setup
  $0 menu    # Interactive menu
  $0 test    # Test connections

EOF
        exit 1
        ;;
esac
